### ISSUE TITLE
Issues with upgrading

### ISSUE THREAD

**Issue by Duke-of-Lizard** [emerald-geomodelling/EmeraldTriangles#7]
I get this issue when trying to upgrade to the latest version of EmeraldTriangles. Any ideas why this might happen?

```
craigchristensen@craigwilliammac EMeraldTriangles % pip install emeraldtriangles --upgrade
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/UNKNOWN
sysconfig: /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Requirement already satisfied: emeraldtriangles in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (0.0.5)
Collecting emeraldtriangles
  Using cached emeraldtriangles-0.0.10.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3l/8lgw2hg14yq6m46r3nhjfn240000gn/T/pip-install-sxxp8z9c/emeraldtriangles_49695282388a4e69a81c9ae557825c74/setup.py'"'"'; __file__='"'"'/private/var/folders/3l/8lgw2hg14yq6m46r3nhjfn240000gn/T/pip-install-sxxp8z9c/emeraldtriangles_49695282388a4e69a81c9ae557825c74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3l/8lgw2hg14yq6m46r3nhjfn240000gn/T/pip-pip-egg-info-eudnlk44
         cwd: /private/var/folders/3l/8lgw2hg14yq6m46r3nhjfn240000gn/T/pip-install-sxxp8z9c/emeraldtriangles_49695282388a4e69a81c9ae557825c74/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3l/8lgw2hg14yq6m46r3nhjfn240000gn/T/pip-install-sxxp8z9c/emeraldtriangles_49695282388a4e69a81c9ae557825c74/setup.py", line 7, in <module>
        include_dirs = [a for a in (a.strip() for a in subprocess.check_output(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
    ----------------------------------------

```

![image](https://user-images.githubusercontent.com/61405744/118673668-7b66b380-b7f9-11eb-9bfe-e0ef18b0f6d1.png)

**Comment by redhog** [comment]
brew install pkg-config
